export const ADD_CARD = 'ADD_CARD';
export const REMOVE_CARD = 'REMOVE_CARD';
export const CHANGE_TITLE_CARD = 'CHANGE_TITLE_CARD';
export const CHANGE_DESCRIPTION_CARD = 'CHANGE_DESCRIPTION_CARD';

export const CHANGE_TITLE_LIST = 'CHANGE_TITLE_LIST';

export const ADD_COMMENT = 'ADD_COMMENT';
export const DEL_COMMENT = 'DEL_COMMENT';
